Getting datadir from configuration instead of hardcoding + sanity check of it's value

diff --git a/templates/simple_restore.sh.erb b/templates/simple_restore.sh.erb
--- a/templates/simple_restore.sh.erb
+++ b/templates/simple_restore.sh.erb
@@ -14,12 +14,21 @@ timestamp=`date +%Y%m%dT%H%M%S`
 backup_bin='/usr/bin/innobackupex'
 use_memory='<%= @use_memory %>' # how much memory the restore process may take
 servers=(<% @db_servers.each do |server| -%><%= server %> <% end -%>)
+datadir=`mysqld --verbose --help 2>&1 | egrep 'datadir\s+' | awk '{print $2}'`
 
 # things to check in advance
+# - is the datadir a recognized value
 # - is mysql really stopped
 # - does the backup dir in question exist
 # - if possible, check if the other db servers in the cluster are stopped too
 # - guesstimate if there is enough space for the procedure
+
+if [ "$datadir" -eq "/var/lib/mysql/" ] || [ "$datadir" -eq "/var/lib/percona-server/" ] ; then
+    echo "MySQL's datadir is '${datadir}', and that is a valid value."
+else
+    echo "ERROR, MySQL's datadir is '${datadir}', and that is not value I recognize."
+    exit 1
+fi
 
 if [ -z "$backup" ]; then
 	echo "ERROR: You did not give me a valid backup to restore as my first parameter"
@@ -90,14 +99,14 @@ ${backup_bin} --use-memory=${use_memory} --apply-log --rebuild-indexes ${backup_
 # move the old data out of the way
 echo "### Moving the old data out of the way ###"
 mkdir -p ${restore_backup_dir}/backup_before_restore_of_${timestamp}
-mv /var/lib/mysql/* ${restore_backup_dir}/backup_before_restore_of_${timestamp}
+mv ${datadir}* ${restore_backup_dir}/backup_before_restore_of_${timestamp}
 
 echo "### Copying back the content of the backup ###"
 ${backup_bin} --copy-back ${backup_root_dir}/${backup}
 
 echo "### Fixing some file permissions ###"
-chown -R mysql:mysql /var/lib/mysql
-chmod -R o-rwx /var/lib/mysql
+chown -R mysql:mysql ${datadir}
+chmod -R o-rwx ${datadir}
 
 echo "Backup should now be restored. You may want to clean up the content of '${restore_backup_dir}'."
 echo "Also, you may want to startup up mysql on the other server(s) too, plus restart applications"
